"""
A couple of covenience functions for analysing broker amendments
"""

import pandas as pd


def bram2contab(df: pd.DataFrame, red_field: str, full=False) -> pd.DataFrame:
    """
    Aggregates the Broker amendment table (as a dataframe) into a 2x2 contingency table (similar to the confusion matrix)
    where the rows are indexed by 'Before_amendment'.isNaN() (i.e., value missing if True and available if False)
    and the columns are indexed by 'After_amendment'.isNaN() (i.e., value missing if True and available if False)

    Parameters:
    ----------
        df: pandas DataFrame
            The Brokers amendments table generated by the SQL query in the TheQuery_v2.txt file
        red_field: str
            One of the 37 values/categories in the 'Reduced_amended_field' of the table (e.g. Line.GoodsDescription, LineContainer.LineNum etc)
        full: bool
            If True it will return the full contingency table (i.e., not the reduced 2x2) with the actual Before_amendment values (rows)
            and Adter_amendment values (columns)

    Returns:
    -------
       ...: pd.DataFrame
           The 2x2 contigency matrix with counts for each of the 4 types of change:
           | Updated   Deleted |
           | Inserted  NaN2NaN |
           or the full contingency table
    """
    if full:
        agg_vals = ['Before_amendment', 'After_amendment']
    else:
        agg_vals = [df['Before_amendment'].isna(), df['After_amendment'].isna()]

    return df.query('Reduced_amended_field == @red_field').\
        groupby(agg_vals, dropna=False)['Entry_ID'].nunique().unstack().fillna(0).astype("int")
        # groupby(agg_vals, dropna=False)['Entry_ID'].count().unstack().fillna(0).astype("int")  # old way



def bram2cmperbr(df: pd.DataFrame, red_field: str, flat: bool=False) -> pd.DataFrame:
    """
    Aggregates the Broker amendment table (as a dataframe) into a 2x2 contigency table (similar to the confusion matrix)
    where the rows are indexed by 'Before_amendment'.isNaN() (i.e., value missing if True and available if False)
    and the columns are indexed by 'After_amendment'.isNaN() (i.e., value missing if True and available if False)
    per each broker.

    Parameters:
    ----------
        df: pandas DataFrame
            The Brokers amendments table generated by the SQL query in the TheQuery_v2.txt file
        red_field: str
            One of the 37 values/categories in the 'Reduced_amended_field' of the table (e.g. Line.GoodsDescription, LineContainer.LineNum etc)
        flat: bool
            If True it will flatten the 2x2 contigency table as 4 columns, named 'Updated', 'Deleted', 'Inserted' and 'None2None'.
            Otherwise (default) each Broker will have 2 rows.

    Returns:
    -------
       pb_df: pd.DataFrame
           The 2x2 contigency matrix  (one PER EACH BROKER) with counts for each of the 4 types of change.
    """

    #   .count().unstack().reset_index().rename_axis(None, axis=1)\  # old way
    pb_df = df.query('Reduced_amended_field == @red_field').groupby(['Broker', df['Before_amendment'].isna(), df['After_amendment'].isna()])['Entry_ID']\
        .nunique().unstack().reset_index().rename_axis(None, axis=1)\
        .rename(columns={False: 'After_am_False', True: 'After_am_True'})
    if flat:
        # UDIN for Updated, Deleted, Inserted and None2None:
        # Use "Before_amendment" for multilevel column indexing and then rename to single-level columns:
        pb_df = pb_df.set_index(['Broker', 'Before_amendment']).unstack(1).\
            set_axis(["Updated", "Inserted", "Deleted", "None2None"], axis=1)
        pb_df = pb_df.assign(Total=pb_df.sum(axis=1, numeric_only=True))
        # swap the order "Inserted" and "Deleted" for color consistency in the plots:
        pb_df = pb_df[['Updated',  'Deleted', 'Inserted', 'None2None', 'Total']]
    return pb_df



def bram2fullcmpb(df: pd.DataFrame, red_field: str, csum_thresh: int, rsum_thresh: int=None) -> pd.DataFrame:
    """
    Aggregates the Broker amendment table (as a dataframe) into a contingency table
    where the rows are indexed by 'Before_amendment' values
    and the columns are indexed by 'After_amendment' values
    per each broker.

    Parameters:
    ----------
        df: pandas DataFrame
            The Brokers amendments table generated by the SQL query in the TheQuery_v2.txt file
        red_field: str
            One of the 37 values/categories in the 'Reduced_amended_field' of the table (e.g. Line.GoodsDescription, LineContainer.LineNum etc)
        csum_thresh: int
            The minimum value of the sum of the counts (ACROSS the numeric columns, i.e., along a row) to keep the row
        rsum_thresh: int
            If provided, the minimum value of the sum of the counts (ALONG a numeric columns, across the rows) to keep the column

    Returns:
    -------
       dmatrix: pd.DataFrame
           The contigency matrix (one PER EACH BROKER) with counts for each Before-After type of the of change.
    """

    #   ['Entry_ID'].count().unstack().reset_index().rename_axis(None, axis=1)  # old_way
    dmatrix = df.query('Reduced_amended_field == @red_field').groupby(['Broker', 'Before_amendment', 'After_amendment'], dropna=False)\
        ['Entry_ID'].nunique().unstack().reset_index().rename_axis(None, axis=1)
    dmatrix = dmatrix.assign(After_am_Total=dmatrix.sum(axis=1, numeric_only=True))

    if rsum_thresh:
        tmp_ser = dmatrix.drop(columns='Before_amendment').sum(axis=0, numeric_only=True) < rsum_thresh
        dmatrix.drop(tmp_ser.index[tmp_ser], axis=1, inplace=True)

    return dmatrix.query('After_am_Total >= @csum_thresh').set_index(['Broker', 'Before_amendment'])



def bram2ts(df: pd.DataFrame, red_field: str, dtp: str="Q", full=False) -> pd.DataFrame:
    """
    Aggregates the Broker amendment table (as a dataframe) into multiple time series (up to 4, based on the 2x2 contigency table above)
    where the rows are indexed by the combinations of 'Before_amendment'.isNaN() and 'After_amendment'.isNaN() values

    Parameters:
    ----------
        df: pandas DataFrame
            The Brokers amendments table generated by the SQL query in the TheQuery_v2.txt file
        red_field: str
            One of the 37 values/categories in the 'Reduced_amended_field' of the table (e.g. Line.GoodsDescription, LineContainer.LineNum etc)
        dtp: str
            One of the allowed datetime period values, in this case quarter (Q) as the default value
        full: bool
            If True it will return the full contingency table (i.e., not the reduced 2x2) with the actual Before_amendment values (rows)
            and Adter_amendment values (columns)

    Returns:
    -------
       dts: pd.DataFrame
           One or more of the timeseries of Updated, Deleted, Inserted and/or None2None counts for the amended field
           Optionall, if full, then the actual Before/After_amendment values are used as the index

    Note: add  .reset_index().rename_axis(None, axis=1)   to convert the multindex into two columns.
        In this case use the following command for plotting the timeseries:   returned_df.filter(like='Q', axis=1).T.plot(...)
    """

    if full:
        agg_vals = ['Before_amendment', 'After_amendment', pd.to_datetime(df['Amendment_date']).dt.to_period('Q')]
    else:
        agg_vals = [df['Before_amendment'].isna(), df['After_amendment'].isna(), pd.to_datetime(df['Amendment_date']).dt.to_period(dtp)]

    return df.query('Reduced_amended_field == @red_field').\
        groupby(agg_vals, dropna=False)['Entry_ID'].nunique().unstack().fillna(0).astype("int")
        # groupby(agg_vals, dropna=False)['Entry_ID'].count().unstack().fillna(0).astype("int")  # old_way
